// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const colors = {
 "primaryHighEmphasis": "rgba(29, 33, 52, 1)",
 "primaryMediumEmphasis": "rgba(60, 73, 104, 1)",
 "primaryLowEmphasis": "rgba(97, 110, 145, 1)",
 "primaryDisabled": "rgba(171, 179, 199, 1)",
 "primaryOutline": "rgba(212, 217, 228, 1)",
 "primarySubtleBackground": "rgba(239, 241, 244, 1)",
 "black": "rgba(0, 0, 0, 1)",
 "white": "rgba(255, 255, 255, 1)",
 "secondaryDarkHighEmphasis": "rgba(252, 252, 252, 1)",
 "secondaryDarkMediumEmphasis": "rgba(165, 165, 165, 1)",
 "secondaryDarkLowEmphasis": "rgba(107, 107, 107, 1)",
 "secondaryDarkDisabled": "rgba(63, 63, 63, 1)",
 "secondaryDarkOutline": "rgba(44, 44, 44, 1)",
 "secondaryDarkSubtleOutline": "rgba(20, 20, 20, 1)",
 "secondaryLightHighEmphasis": "rgba(10, 10, 10, 1)",
 "secondaryLightMediumEmphasis": "rgba(78, 78, 78, 1)",
 "secondaryLightLowEmphasis": "rgba(136, 136, 136, 1)",
 "secondaryLightDisabled": "rgba(194, 194, 194, 1)",
 "secondaryLightOutline": "rgba(218, 218, 218, 1)",
 "secondaryLightSubtleOutline": "rgba(242, 242, 242, 1)",
 "success": "rgba(30, 255, 133, 1)",
 "cta01": "rgba(0, 102, 219, 1)",
 "cta02": "rgba(0, 102, 219, 1)",
 "cta03": "rgba(0, 102, 219, 1)",
 "error": "rgba(252, 46, 71, 1)",
 "indication01": "rgba(34, 30, 255, 1)",
 "indication02": "rgba(169, 30, 255, 1)",
 "indication03": "rgba(255, 124, 30, 1)",
 "indication04": "rgba(255, 216, 30, 1)"
}

export default colors;