// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontFamilies = {
 "h1": "Raleway",
 "h2": "Raleway",
 "h3": "Raleway",
 "h4": "Raleway",
 "body1": "IBM Plex Sans",
 "body2": "IBM Plex Sans",
 "caption1": "IBM Plex Sans",
 "caption2": "IBM Plex Sans",
 "caption3": "IBM Plex Sans",
 "caption4": "IBM Plex Sans",
 "footnote1": "IBM Plex Sans",
 "footnote2": "IBM Plex Sans",
 "buttonRegular": "IBM Plex Sans",
 "buttonSmall": "IBM Plex Sans",
 "buttonTiny": "IBM Plex Sans"
}

export default fontFamilies;