// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontWeights = {
 "h1": 700,
 "h2": 700,
 "h3": 700,
 "h4": 700,
 "body1": 400,
 "body2": 500,
 "caption1": 400,
 "caption2": 500,
 "caption3": 400,
 "caption4": 500,
 "footnote1": 400,
 "footnote2": 500,
 "buttonRegular": 500,
 "buttonSmall": 500,
 "buttonTiny": 500
}

export default fontWeights;