// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontSizes = {
 "h1": "2rem",
 "h2": "1.5rem",
 "h3": "1.125rem",
 "h4": "1rem",
 "body1": "1rem",
 "body2": "1rem",
 "caption1": "0.875rem",
 "caption2": "0.875rem",
 "caption3": "0.75rem",
 "caption4": "0.75rem",
 "footnote1": "0.625rem",
 "footnote2": "0.625rem",
 "buttonRegular": "0.875rem",
 "buttonSmall": "0.75rem",
 "buttonTiny": "0.625rem"
}

export default fontSizes;