// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const spacing = {
 "spacingHorizontal2": "4rem",
 "spacingHorizontal4": "4rem",
 "spacingHorizontal8": "4rem",
 "spacingHorizontal16": "4rem",
 "spacingHorizontal24": "4rem",
 "spacingHorizontal32": "4rem",
 "spacingHorizontal64": "4rem",
 "spacingHorizontalBase": "4rem",
 "spacingVertical2": "0.125rem",
 "spacingVertical4": "0.25rem",
 "spacingVertical8": "0.5rem",
 "spacingVertical16": "1rem",
 "spacingVertical24": "1.5rem",
 "spacingVertical32": "2rem",
 "spacingVertical64": "4rem",
 "spacingVerticalBase": "2.25rem"
}

export default spacing;